#pragma config(Sensor, S1,     colorSensor,    sensorEV3_Color, modeEV3Color_Reflected)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro)
#pragma config(Sensor, S3,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Colour sensor modes
0 - modeEV3Color_Reflected
1 - modeEV3Color_Ambient
2 - modeEV3Color_Color
3 - modeEV3Color_Reflected_Raw
4 - modeEV3Color_RGB_Raw
5 - modeEV3Color_Calibration - Not utilized
*/

// - 70 to -50 is stable

task main()
{
	while (true)
	{

		//displayBigTextLine(4, "Reflected: %d", SensorValue[Colour]); //print on the screen the sensor value
		//if (SensorValue[Colour] == 0) // stops the motors if the robot not on surface
		//{
		//	setMotorSpeed(leftMotor, 0);
		//	setMotorSpeed(rightMotor, 0);
		//}
		//if (SensorValue[Colour] > 74) //  the robot goes straight if the color is white
		//{
		//	setMotorSpeed(leftMotor, 20);
		//	setMotorSpeed(rightMotor, 20);
		//}
		//if (SensorValue[Colour] <= 10 && SensorValue[Colour] > 0) // the robot turns right if it is on black
		//{
		//	setMotorSpeed(leftMotor, 12);
		//	setMotorSpeed(rightMotor, 0);
		//}

		//if (SensorValue[Colour] > 45 && SensorValue[Colour] < 70) // the robut turns right if the color is slightly white on the left side of the black line
		//{
		//	setMotorSpeed(leftMotor, 12);
		//	setMotorSpeed(rightMotor, 0);
		//}
		//if (SensorValue[Colour] < 40 && SensorValue[Colour] > 10) // the robut turns left if the color is slightly white on the right side of the black line
		//{
		//	setMotorSpeed(rightMotor, 12);
		//	setMotorSpeed(leftMotor, 0);
		//}

		if (getGyroDegrees(gyroSensor) > -50 ) {

		}

	}
}
